<a href="https://colab.research.google.com/github/Aakarsh204/PyTorch-Deep-Learning/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors
### Creating Tensors
PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                       [[1,2,3],[4,5,6],[7,8,9]],
                       [[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([3, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

###Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks work is they begin with a randomly generated tensors and then adjust those weights to better suit our data.

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3882, 0.0874, 0.5839, 0.6294],
        [0.8046, 0.9596, 0.8437, 0.3058],
        [0.2090, 0.4353, 0.3053, 0.0194]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(4,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange
torch.arange(1, 11)
# torch.arange(start, end, step)
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor errors you'll most likely run into are:
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #datatype of tensor, using none sets default
                               device = None, # what device the tensor is on (Ex. cuda, cpu)
                               requires_grad = False) # whether to track gradients or not)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

###Getting information from tensors (attributes)

1. Tensors not the right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`
**Note: tensor.size() is a function while tensor.shape is an attribute**

In [ ]:
# Create a tensor
some_tensor = torch.rand(size=(3, 4), dtype=torch.float64)

# Find out details about it
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.4035, 0.5010, 0.8062, 0.8245],
        [0.6963, 0.6415, 0.0322, 0.2614],
        [0.6870, 0.3050, 0.9423, 0.5296]], dtype=torch.float64)
Datatype of Tensor: torch.float64
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


from ast import Mult
### Manipulating Tensors

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Add to tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Subtract from tensor
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Multiply tensor
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Divide tensor
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Element wise tensor multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication or Dot product
tensor1 = torch.rand(2, 3)
print(tensor1)
tensor2 = torch.rand(3, 2)
print(tensor2)

torch.matmul(tensor1, tensor2)
torch.mm(tensor1, tensor2) # torch.mm() is an alias for torch.matmul()

tensor([[0.6625, 0.6817, 0.9780],
        [0.0356, 0.1121, 0.1003]])
tensor([[0.4904, 0.9254],
        [0.1218, 0.0150],
        [0.4890, 0.7423]])


tensor([[0.8861, 1.3493],
        [0.0802, 0.1091]])

To fix our shape issues while multiplying two tensors, we can use the transpose() method.

Transpose switches the axes or dimensions of a given tensor.


In [ ]:
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
print(tensor)
tensor.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [ ]:
print(tensor.T)
tensor.T.shape

tensor([[1, 4],
        [2, 5],
        [3, 6]])


torch.Size([3, 2])

In [ ]:
torch.mm(tensor, tensor.T)

tensor([[14, 32],
        [32, 77]])

## Finding the min, max, mean, sum, avg etc (tensor aggregation)


In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# Mean does not work on int or long, only float or complex dtypes

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the index of the of min value in tensor
x.argmin()

tensor(0)

In [ ]:
# Find the index of the max value in tensor
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tnsor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all '1' dimensions from a tensor
* Unsqueeze - Adds a '1' dimension to the tensor
* Permute - Return a view of the input with the dimensions swapped in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x because view is just a representation of x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all '1' dimensions
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor after squeezing: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# torch.unsqueeze() - adds a single dimension to a tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor after unsqueezing: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor after squeezing: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])

New tensor after unsqueezing: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of the tensor
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour channels]

# Permute the original tensor to get colour channels first
x_permuted = x_original.permute(2, 0, 1) # shifts axis 2->0, 0->1, 1->2

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing in tensors

Indexing with PyTorch is similar to indexing with NumPy

In [71]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
# Indexing on dim 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
# Indexing on dim 1
x[0, 1]

tensor([4, 5, 6])

In [74]:
# Indexing on dim 2
x[0, 1, 2]

tensor(6)

In [75]:
# Using ':' selects 'all' elements in that specific dimension
x[0, :, 1]

tensor([2, 5, 8])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
PyTorch has functionality to interact with it.

* NumPy array to PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy array -> `torch.Tensor.numpy()`

In [1]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
array.dtype

dtype('float64')

In [3]:
# By default NumPy has a datatype of float64 which means while converting to tensor you should change to float 32
tensor = tensor.type(torch.float32)
tensor.dtype

torch.float32

In [4]:
# Tensor to NumPy
tensor = torch.ones(8)
numpy_array = tensor.numpy()
tensor, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

When we use random numbers in our neural networks but want to replicate the same randomness, we use this feature

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [32]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8335, 0.4926, 0.0304, 0.4364],
        [0.6956, 0.1851, 0.9125, 0.3246],
        [0.5461, 0.7121, 0.1484, 0.1033]])
tensor([[0.9476, 0.2716, 0.8046, 0.6660],
        [0.2695, 0.7046, 0.2112, 0.4035],
        [0.8251, 0.0556, 0.8880, 0.4032]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [34]:
# Random but reproducible tensors
# Set the random seed
RANDOM_SEED = 69
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs

### Getting a GPU

1. Use Google Colab for a free gpu
2. Use your own gpu
3. Use cloud computing - GCP, AWS, Azure

In [1]:
!nvidia-smi

Sun Sep  1 14:52:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
# Check for GPU access in PyTorch
import torch
torch.cuda.is_available()

True

In [2]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [3]:
# Count the number of GPUs
torch.cuda.device_count()

1

### Putting tensors and models on the GPU

In [4]:
# Create a tensor
tensor = torch.tensor([1, 2, 3, 4])
print(tensor, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4], device='cuda:0')

### Moving tensors back to CPU

In [7]:
# If tensor is on GPU, it can't transform into NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# Fixing it
tensor_cpu = tensor_on_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3, 4])